import type { Invoice, InvoiceCustomer } from "../../lib/invoice-types"
import { formatRupiah } from "../../lib/format"

function value(snapshot: Record<string, unknown> | null, key: string) { return String(snapshot?.[key] ?? "") }

export function InvoiceDocument({ invoice, customer, logoDataUrl }: { invoice: Invoice; customer?: InvoiceCustomer | null; logoDataUrl?: string | null }) {
  const customerSnapshot = invoice.customerSnapshot
  const customerName = value(customerSnapshot, "name") || customer?.name || "Pelanggan"
  const address = [value(customerSnapshot, "addressLine1") || customer?.addressLine1, value(customerSnapshot, "addressLine2") || customer?.addressLine2, value(customerSnapshot, "district") || customer?.district, value(customerSnapshot, "city") || customer?.city, value(customerSnapshot, "province") || customer?.province, value(customerSnapshot, "postalCode") || customer?.postalCode].filter(Boolean).join(", ")
  const sender = invoice.senderSnapshot
  const rows = [...invoice.items, ...Array.from({ length: Math.max(0, 3 - invoice.items.length) }, (_, index) => ({ id: `blank-${index}`, description: "", quantityScaled: 0, unitLabel: "", unitPrice: 0, lineTotal: 0, sortOrder: 99 }))]
  return (
    <article className="invoice-paper" data-invoice-document>
      <style>{INVOICE_CSS}</style>
      <header className="invoice-header"><div className="invoice-brand">{logoDataUrl ? <img src={logoDataUrl} alt="Logo company" /> : <strong>{value(sender, "name") || "Company"}</strong>}</div><h1>INVOICE</h1></header>
      <section className="invoice-meta"><div><small>KEPADA</small><h2>{customerName}</h2><p>{value(customerSnapshot, "phone") || customer?.phone || ""}</p><p>{address}</p></div><dl><div><dt>No</dt><dd>{invoice.invoiceNumber || "DRAFT"}</dd></div><div><dt>Tgl</dt><dd>{invoice.issueDate}</dd></div><div><dt>Jatuh Tempo</dt><dd>{invoice.dueDate}</dd></div></dl></section>
      <table><thead><tr><th>NO</th><th>DESKRIPSI</th><th>JUMLAH</th><th>HARGA</th><th>TOTAL</th></tr></thead><tbody>{rows.map((item, index) => <tr key={item.id}><td>{item.description ? index + 1 : ""}</td><td>{item.description}</td><td>{item.description ? `${(item.quantityScaled / 1000).toLocaleString("id-ID")} ${item.unitLabel}` : ""}</td><td>{item.description ? formatRupiah(item.unitPrice) : ""}</td><td>{item.description ? formatRupiah(item.lineTotal) : ""}</td></tr>)}</tbody></table>
      <section className="invoice-summary"><div><small>PEMBAYARAN</small>{(invoice.paymentInstructionsSnapshot ?? []).map((item, index) => <p key={index}><strong>{item.name}</strong> {item.accountNumber}<br />a.n. {item.accountHolder}</p>)}{invoice.shippingMethod && <p><small>PENGIRIMAN</small><br />{invoice.shippingMethod}</p>}</div><dl><div><dt>Subtotal</dt><dd>{formatRupiah(invoice.subtotal)}</dd></div>{invoice.discountAmount > 0 && <div><dt>Diskon</dt><dd>-{formatRupiah(invoice.discountAmount)}</dd></div>}{invoice.shippingAmount > 0 && <div><dt>Pengiriman</dt><dd>{formatRupiah(invoice.shippingAmount)}</dd></div>}{invoice.taxAmount > 0 && <div><dt>Pajak</dt><dd>{formatRupiah(invoice.taxAmount)}</dd></div>}<div className="grand"><dt>Total Keseluruhan</dt><dd>{formatRupiah(invoice.grandTotal)}</dd></div></dl></section>
      <footer><span>Konfirmasi Pembayaran<br /><strong>{value(sender, "phone")}</strong></span><strong>{value(sender, "email")}</strong></footer>
      {invoice.status === "DRAFT" && <div className="invoice-watermark">DRAFT</div>}{invoice.status === "VOID" && <div className="invoice-watermark">DIBATALKAN</div>}
    </article>
  )
}

export const INVOICE_CSS = `
.invoice-paper{position:relative;box-sizing:border-box;display:flex;flex-direction:column;width:210mm;min-height:297mm;padding:8mm 21mm 13mm;background:#fff;color:#111;font-family:Poppins,Arial,sans-serif;font-size:12px}.invoice-header{display:flex;min-height:38mm;align-items:flex-start;justify-content:space-between}.invoice-brand{font-size:24px;max-width:82mm}.invoice-brand img{display:block;max-width:82mm;max-height:24mm;object-fit:contain;object-position:left top}.invoice-header h1{font-size:60px;line-height:.9;font-weight:900;margin:0}.invoice-meta{display:grid;grid-template-columns:1fr 48mm;gap:12mm;margin-bottom:8mm}.invoice-meta small,.invoice-summary small{font-weight:800;letter-spacing:.08em}.invoice-meta h2{font-size:23px;margin:2mm 0 1mm;font-weight:900}.invoice-meta p{margin:1mm 0}.invoice-meta dl{margin:0}.invoice-meta dl div,.invoice-summary dl div{display:flex;justify-content:space-between;gap:4mm}.invoice-meta dt{font-weight:700}.invoice-meta dd,.invoice-summary dd{margin:0;text-align:right}table{width:100%;border-collapse:collapse;table-layout:fixed}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}th{background:#d9d9d9;color:#000;padding:3mm 2mm;text-align:left;font-size:10px}th:first-child,td:first-child{width:14mm;text-align:center}th:nth-child(3),td:nth-child(3){width:37mm;text-align:center}th:nth-child(4),th:nth-child(5),td:nth-child(4),td:nth-child(5){width:36mm;text-align:right}td{padding:3mm 2mm;border-bottom:1px solid #ddd;vertical-align:top;overflow-wrap:anywhere;min-height:9mm}.invoice-summary{display:grid;grid-template-columns:1fr 78mm;gap:10mm;margin-top:8mm;break-inside:avoid;page-break-inside:avoid}.invoice-summary p{margin:2mm 0}.invoice-summary dl{margin:0}.invoice-summary dl div{padding:1.5mm 2mm}.invoice-summary .grand{margin-top:2mm;background:#d9d9d9;padding:3mm 2mm;font-weight:900}footer{display:flex;justify-content:space-between;align-items:flex-end;margin-top:auto;padding-top:10mm;break-inside:avoid;page-break-inside:avoid}footer>strong{color:#1d73e8}.invoice-watermark{position:absolute;inset:45% 0 auto;transform:rotate(-20deg);text-align:center;font-size:56px;font-weight:900;color:rgba(180,0,0,.16);pointer-events:none}@media(max-width:850px){.invoice-paper{transform-origin:top left}}@media print{body{background:#fff}.invoice-paper{box-shadow:none;margin:0}@page{size:A4;margin:0}}
`
