migrate((app) => {
  const users = app.findCollectionByNameOrId("users"); const companies = app.findCollectionByNameOrId("companies")
  const create = (name, indexes = []) => { let collection; try { collection = app.findCollectionByNameOrId(name) } catch { collection = new Collection({ type: "base", name, listRule: null, viewRule: null, createRule: null, updateRule: null, deleteRule: null, indexes: [] }) }; for (const index of indexes) { const indexName = String(index).match(/INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?([^\s]+)/i)?.[1] || index; if (!collection.indexes.some((item) => String(item).includes(indexName))) collection.indexes.push(index) }; return collection }
  const field = (collection, name, factory) => { if (!collection.fields.getByName(name)) collection.fields.add(factory()) }
  const text = (collection, name, required = false, max = 255) => field(collection, name, () => new TextField({ name, required, max }))
  const integer = (collection, name, required = false, min = 0, max = 1_000_000_000) => field(collection, name, () => new NumberField({ name, required, min, max, onlyInt: true }))
  const json = (collection, name, required = false, maxSize = 262_144) => field(collection, name, () => new JSONField({ name, required, maxSize }))
  const select = (collection, name, values) => field(collection, name, () => new SelectField({ name, required: true, maxSelect: 1, values }))
  const relation = (collection, name, target, required = false) => field(collection, name, () => new RelationField({ name, collectionId: target.id, required, maxSelect: 1, cascadeDelete: false }))
  const scope = (collection) => { relation(collection, "tenant_id", users, true); relation(collection, "company_id", companies, true); integer(collection, "data_epoch", true, 1) }
  const timestamps = (collection) => { field(collection, "created", () => new AutodateField({ name: "created", onCreate: true, onUpdate: false })); field(collection, "updated", () => new AutodateField({ name: "updated", onCreate: true, onUpdate: true })) }

  const documents = create("document_inbox", ["CREATE INDEX idx_document_scope_status ON document_inbox (tenant_id, company_id, data_epoch, status, created)", "CREATE INDEX idx_document_hash ON document_inbox (tenant_id, company_id, data_epoch, sha256)"])
  scope(documents); select(documents, "source", ["CAMERA", "UPLOAD", "SHARE_TARGET"]); text(documents, "filename", true, 255); text(documents, "mime", true, 100); integer(documents, "byte_size", true, 1, 8_388_608); text(documents, "sha256", true, 64)
  field(documents, "file", () => new FileField({ name: "file", required: true, maxSelect: 1, maxSize: 8_388_608, protected: true, mimeTypes: ["image/png", "image/jpeg", "image/webp", "application/pdf"] }))
  json(documents, "content_base64", true, 12_000_000)
  select(documents, "status", ["UNPROCESSED", "REVIEW_READY", "LINKED", "ARCHIVED"]); text(documents, "duplicate_of_id", false, 100); text(documents, "linked_transaction_id", false, 100); text(documents, "linked_payment_id", false, 100); text(documents, "link_origin", false, 30); json(documents, "original_ledger_snapshot", false, 500_000); text(documents, "unlink_reason", false, 500); integer(documents, "revision", true, 1); timestamps(documents); app.save(documents)

  const extractions = create("document_extractions", ["CREATE INDEX idx_extraction_document ON document_extractions (tenant_id, company_id, document_id, created)"])
  scope(extractions); relation(extractions, "document_id", documents, true); text(extractions, "schema_version", true, 50); text(extractions, "model", true, 200); text(extractions, "provider", false, 100); text(extractions, "prompt_version", true, 50); json(extractions, "result", true, 500_000); json(extractions, "warnings", false, 50_000); timestamps(extractions); app.save(extractions)

  const jobs = create("ai_jobs", ["CREATE UNIQUE INDEX idx_ai_request_scope ON ai_jobs (tenant_id, company_id, data_epoch, request_key)", "CREATE INDEX idx_ai_queue ON ai_jobs (status, lease_until, created)"])
  scope(jobs); relation(jobs, "document_id", documents, true); text(jobs, "request_key", true, 100); text(jobs, "input_hash", true, 64); text(jobs, "schema_version", true, 50); select(jobs, "status", ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", "UNKNOWN"]); integer(jobs, "attempt_count", false, 0, 20); text(jobs, "lease_owner", false, 100); text(jobs, "lease_until", false, 40); integer(jobs, "generation", true, 1); text(jobs, "provider_request_id", false, 255); text(jobs, "model", false, 200); text(jobs, "error_code", false, 100); integer(jobs, "input_tokens", false, 0); integer(jobs, "output_tokens", false, 0); text(jobs, "cost_usd", false, 50); relation(jobs, "extraction_id", extractions, false); timestamps(jobs); app.save(jobs)

  const commands = create("document_commands", ["CREATE UNIQUE INDEX idx_document_command_scope ON document_commands (tenant_id, company_id, data_epoch, command_key)"])
  scope(commands); text(commands, "command_key", true, 100); text(commands, "action", true, 60); text(commands, "request_hash", true, 64); integer(commands, "response_status", true, 200, 599); json(commands, "response_body", true, 1_000_000); timestamps(commands); app.save(commands)

  const subscriptions = create("push_subscriptions", ["CREATE UNIQUE INDEX idx_push_endpoint ON push_subscriptions (tenant_id, endpoint_hash)", "CREATE INDEX idx_push_user_active ON push_subscriptions (tenant_id, revoked_at)"])
  relation(subscriptions, "tenant_id", users, true); text(subscriptions, "endpoint", true, 2000); text(subscriptions, "endpoint_hash", true, 64); text(subscriptions, "p256dh", true, 500); text(subscriptions, "auth_key", true, 500); json(subscriptions, "company_ids", false, 50_000); json(subscriptions, "preferences", false, 50_000); text(subscriptions, "timezone", true, 60); integer(subscriptions, "quiet_start_hour", false, 0, 23); integer(subscriptions, "quiet_end_hour", false, 0, 23); text(subscriptions, "revoked_at", false, 40); text(subscriptions, "last_seen_at", true, 40); timestamps(subscriptions); app.save(subscriptions)

  const deliveries = create("notification_deliveries", ["CREATE UNIQUE INDEX idx_notification_dedupe ON notification_deliveries (dedupe_key)", "CREATE INDEX idx_notification_queue ON notification_deliveries (status, scheduled_at)"])
  relation(deliveries, "tenant_id", users, true); relation(deliveries, "subscription_id", subscriptions, true); text(deliveries, "company_id", false, 100); text(deliveries, "event_type", true, 80); text(deliveries, "resource_id", true, 100); text(deliveries, "dedupe_key", true, 255); select(deliveries, "status", ["PENDING", "LEASED", "SENT", "RETRYABLE_FAILED", "PERMANENTLY_FAILED", "CANCELLED"]); integer(deliveries, "attempt_count", false, 0, 20); text(deliveries, "scheduled_at", true, 40); text(deliveries, "lease_until", false, 40); text(deliveries, "sent_at", false, 40); text(deliveries, "last_error", false, 500); timestamps(deliveries); app.save(deliveries)
}, () => { /* Private financial documents are retained on application rollback. */ })
