function body(event) { return event.requestInfo().body || {} }
function json(record, field, fallback) { const raw = record.get(field); if (Array.isArray(raw) || (raw && typeof raw === "object" && typeof raw.length === "number" && typeof raw[0] === "number")) { try { return JSON.parse(String.fromCharCode(...raw)) } catch { return fallback } }; if (raw !== null && raw !== undefined && typeof raw !== "string" && typeof raw.get !== "function") return raw; try { const exported = JSON.parse(JSON.stringify(record.publicExport()))[field]; if (Array.isArray(exported) && exported.every((item) => typeof item === "number")) return JSON.parse(String.fromCharCode(...exported)); if (exported !== undefined) return exported } catch { /* fallback */ }; try { return JSON.parse(record.getString(field)) } catch { return fallback } }
function bytesFromBase64(value) { const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"; const text = String(value || "").replace(/=+$/, ""); const output = []; let buffer = 0; let bits = 0; for (let index = 0; index < text.length; index += 1) { const digit = alphabet.indexOf(text[index]); if (digit < 0) throw new ApiError(400, "Data dokumen tidak valid"); buffer = (buffer << 6) | digit; bits += 6; if (bits >= 8) { bits -= 8; output.push((buffer >> bits) & 255) } }; return new Uint8Array(output) }
function detect(bytes) {
  if (bytes.length >= 8 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) return "image/png"
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return "image/jpeg"
  if (bytes.length >= 12 && String.fromCharCode(...bytes.slice(0, 4)) === "RIFF" && String.fromCharCode(...bytes.slice(8, 12)) === "WEBP") return "image/webp"
  if (bytes.length >= 5 && String.fromCharCode(...bytes.slice(0, 5)) === "%PDF-") return "application/pdf"
  throw new ApiError(415, "Jenis dokumen tidak didukung atau file rusak")
}
function scope(event, input, writable) {
  const tenantId = event.auth.id; const companyId = String(input.companyId || ""); const epoch = Number(input.dataEpoch || 0); let company
  try { company = $app.findRecordById("companies", companyId) } catch { throw new ApiError(404, "Company tidak ditemukan") }
  if (company.getString("tenant_id") !== tenantId || company.getInt("data_epoch") !== epoch) throw new ApiError(404, "Company tidak ditemukan")
  if (writable && company.getString("status") !== "ACTIVE") throw new ApiError(409, "Company diarsipkan")
  return { tenantId, companyId, epoch }
}
function owned(app, collection, id, s, label) { let record; try { record = app.findRecordById(collection, id) } catch { throw new ApiError(404, `${label} tidak ditemukan`) }; if (record.getString("tenant_id") !== s.tenantId || record.getString("company_id") !== s.companyId || record.getInt("data_epoch") !== s.epoch) throw new ApiError(404, `${label} tidak ditemukan`); return record }
function response(record) { return { id: record.id, tenantId: record.getString("tenant_id"), companyId: record.getString("company_id"), dataEpoch: record.getInt("data_epoch"), source: record.getString("source"), filename: record.getString("filename"), mimeType: record.getString("mime"), byteSize: record.getInt("byte_size"), sha256: record.getString("sha256"), status: record.getString("status"), duplicateOfId: record.getString("duplicate_of_id") || null, linkedTransactionId: record.getString("linked_transaction_id") || null, linkedPaymentId: record.getString("linked_payment_id") || null, revision: record.getInt("revision"), createdAt: record.getString("created"), updatedAt: record.getString("updated") } }
function findAll(app, collection, filter, sort, params) { const rows = []; let offset = 0; while (true) { const page = app.findRecordsByFilter(collection, filter, sort || "", 500, offset, params || {}); rows.push(...page); if (page.length < 500) return rows; offset += page.length } }
function stableStringify(value) { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}` }
function commandHash(action, input) { return $security.sha256(`${action}:${stableStringify(input)}`) }
function replayCommand(tx, s, key, action, hash) { let record; try { record = tx.findFirstRecordByFilter("document_commands", "tenant_id = {:tenant} && company_id = {:company} && data_epoch = {:epoch} && command_key = {:key}", { tenant: s.tenantId, company: s.companyId, epoch: s.epoch, key }) } catch { return null }; if (record.getString("action") !== action || record.getString("request_hash") !== hash) throw new ApiError(409, "Kunci perintah sudah digunakan untuk permintaan lain"); return { status: record.getInt("response_status"), body: json(record, "response_body", {}) } }
function saveCommand(tx, s, key, action, hash, status, result) { tx.save(new Record(tx.findCollectionByNameOrId("document_commands"), { tenant_id: s.tenantId, company_id: s.companyId, data_epoch: s.epoch, command_key: key, action, request_hash: hash, response_status: status, response_body: result })) }
module.exports = { body, bytesFromBase64, commandHash, detect, findAll, json, owned, replayCommand, response, saveCommand, scope, stableStringify }
