function json(record, field, fallback) { const raw = record.get(field); if (Array.isArray(raw) || (raw && typeof raw === "object" && typeof raw.length === "number" && typeof raw[0] === "number")) { try { return JSON.parse(String.fromCharCode(...raw)) } catch { return fallback } }; if (raw && typeof raw === "object" && typeof raw.get !== "function") return raw; try { return JSON.parse(record.getString(field)) } catch { return fallback } }
function all(collection, filter, sort, params) { const rows = []; let offset = 0; while (true) { const page = $app.findRecordsByFilter(collection, filter, sort || "", 500, offset, params || {}); rows.push(...page); if (page.length < 500) return rows; offset += page.length } }
function selected(subscription, companyId, kind) { const companies = json(subscription, "company_ids", []); const preferences = json(subscription, "preferences", {}); return !subscription.getString("revoked_at") && (companies.length === 0 || companies.includes(companyId)) && preferences[kind] !== false }
function quietDelay(subscription) { const offsets = { "Asia/Jakarta": 7, "Asia/Makassar": 8, "Asia/Jayapura": 9, "UTC": 0 }; const offset = Object.prototype.hasOwnProperty.call(offsets, subscription.getString("timezone")) ? offsets[subscription.getString("timezone")] : 7; const local = new Date(Date.now() + offset * 3_600_000); const hour = local.getUTCHours(); const start = subscription.getInt("quiet_start_hour"); const end = subscription.getInt("quiet_end_hour"); const quiet = start === end ? false : start < end ? hour >= start && hour < end : hour >= start || hour < end; if (!quiet) return 0; let hours = (end - hour + 24) % 24; if (!hours) hours = 24; return hours * 3_600_000 - local.getUTCMinutes() * 60_000 - local.getUTCSeconds() * 1000 }
function enqueue(subscription, companyId, type, resourceId) { const key = `${subscription.id}:${type}:${resourceId}`; try { $app.findFirstRecordByFilter("notification_deliveries", "dedupe_key = {:key}", { key }); return false } catch { /* new */ }; try { $app.save(new Record($app.findCollectionByNameOrId("notification_deliveries"), { tenant_id: subscription.getString("tenant_id"), recipient_user_id: subscription.getString("recipient_user_id") || subscription.getString("tenant_id"), subscription_id: subscription.id, company_id: companyId, event_type: type, resource_id: resourceId, dedupe_key: key, status: "PENDING", attempt_count: 0, scheduled_at: new Date().toISOString() })); return true } catch { return false } }
function member(subscription, companyId, app) { return require(`${__hooks}/company_access.js`).actorCanAccessCompany(app || $app, subscription.getString("recipient_user_id") || subscription.getString("tenant_id"), companyId) }
function generate() {
  if ($os.getenv("JORNAL_PUSH_ENABLED") !== "true") return { created: 0 }; let created = 0; const subscriptions = all("push_subscriptions", "revoked_at = ''", "id")
  const reminders = all("invoice_reminders", "status = 'UNREAD'", "created,id"); for (const reminder of reminders) for (const subscription of subscriptions) if (member(subscription, reminder.getString("company_id"), $app) && selected(subscription, reminder.getString("company_id"), "invoice")) created += enqueue(subscription, reminder.getString("company_id"), "INVOICE_OVERDUE", reminder.id) ? 1 : 0
  const documents = all("document_inbox", "status = 'UNPROCESSED' || status = 'REVIEW_READY'", "created,id"); for (const document of documents) for (const subscription of subscriptions) if (member(subscription, document.getString("company_id"), $app) && selected(subscription, document.getString("company_id"), "documents")) created += enqueue(subscription, document.getString("company_id"), "DOCUMENT_REVIEW", `${document.id}:${document.getInt("revision")}`) ? 1 : 0
  const taxItems = all("tax_notifications", "channel = 'IN_APP' && status = 'SENT'", "sent_at,id"); for (const item of taxItems) { const companyIds = [...new Set(all("tax_company_memberships", "tenant_id = {:tenant} && subject_id = {:subject}", "company_id", { tenant: item.getString("tenant_id"), subject: item.getString("subject_id") }).map((membership) => membership.getString("company_id")).filter(Boolean))]; for (const companyId of companyIds) for (const subscription of subscriptions) if ((subscription.getString("recipient_user_id") || subscription.getString("tenant_id")) === (item.getString("recipient_user_id") || item.getString("tenant_id")) && companyIds.every((id) => member(subscription, id, $app)) && selected(subscription, companyId, "tax")) created += enqueue(subscription, companyId, "TAX_AGENDA", item.id) ? 1 : 0 }
  return { created }
}
function applicable(delivery, app) {
  app = app || $app; if ($os.getenv("JORNAL_PUSH_ENABLED") !== "true") return null; let subscription; try { subscription = app.findRecordById("push_subscriptions", delivery.getString("subscription_id")) } catch { return null }; if (subscription.getString("revoked_at") || !member(subscription, delivery.getString("company_id"), app)) return null
  const type = delivery.getString("event_type"); const resource = delivery.getString("resource_id").split(":")[0]; const companyId = delivery.getString("company_id")
  if (type === "INVOICE_OVERDUE") { let reminder; try { reminder = app.findRecordById("invoice_reminders", resource) } catch { return null }; let invoice; try { invoice = app.findRecordById("invoices", reminder.getString("invoice_id")) } catch { return null }; if (!["UNREAD", "READ"].includes(reminder.getString("status")) || invoice.getString("status") !== "UNPAID" || !selected(subscription, companyId, "invoice")) return null; return { title: "Invoice perlu ditagih", body: "Ada invoice lewat jatuh tempo yang perlu diperiksa.", url: `/invoices/${invoice.id}?company=${companyId}`, tag: `invoice-${invoice.id}` } }
  if (type === "DOCUMENT_REVIEW") { let document; try { document = app.findRecordById("document_inbox", resource) } catch { return null }; if (!["UNPROCESSED", "REVIEW_READY"].includes(document.getString("status")) || !selected(subscription, companyId, "documents")) return null; return { title: "Dokumen perlu diperiksa", body: "Dokumen tersimpan di inbox dan belum selesai direview.", url: `/inbox/${document.id}?company=${companyId}`, tag: `document-${document.id}` } }
  if (type === "TAX_AGENDA") { let notification; try { notification = app.findRecordById("tax_notifications", resource) } catch { return null }; if (notification.getString("status") !== "SENT" || !selected(subscription, companyId, "tax")) return null; return { title: "Agenda pajak", body: "Ada kewajiban atau pelaporan pajak yang perlu diperiksa.", url: `/tax?company=${companyId}`, tag: `tax-${resource}` } }
  return null
}
function claim(limit) { const now = new Date().toISOString(); const claimed = []; $app.runInTransaction((tx) => { const rows = tx.findRecordsByFilter("notification_deliveries", "((status = 'PENDING' || status = 'RETRYABLE_FAILED') && scheduled_at <= {:now}) || (status = 'LEASED' && lease_until < {:now})", "scheduled_at,id", Math.max(1, Math.min(100, limit || 25)), 0, { now }); for (const row of rows) { const payload = applicable(row, tx); if (!payload) { row.set("status", "CANCELLED"); row.set("lease_id", ""); row.set("last_error", "Notification is no longer applicable"); tx.save(row); continue }; const subscription = tx.findRecordById("push_subscriptions", row.getString("subscription_id")); const delay = quietDelay(subscription); if (delay > 0) { row.set("status", "PENDING"); row.set("lease_id", ""); row.set("lease_until", ""); row.set("scheduled_at", new Date(Date.now() + delay).toISOString()); tx.save(row); continue }; const leaseId = $security.randomString(32); row.set("status", "LEASED"); row.set("lease_id", leaseId); row.set("lease_until", new Date(Date.now() + 5 * 60_000).toISOString()); tx.save(row); claimed.push({ id: row.id, leaseId, endpoint: subscription.getString("endpoint"), keys: { p256dh: subscription.getString("p256dh"), auth: subscription.getString("auth_key") }, payload }) } }); return claimed }
function validate(id, leaseId) { let row; try { row = $app.findRecordById("notification_deliveries", id) } catch { return false }; if (row.getString("status") !== "LEASED" || row.getString("lease_id") !== leaseId) return false; if (applicable(row, $app)) return true; row.set("status", "CANCELLED"); row.set("lease_id", ""); row.set("lease_until", ""); row.set("last_error", "Notification is no longer applicable"); $app.save(row); return false }
function complete(id, leaseId, outcome, error) { let revoked = false; $app.runInTransaction((tx) => { let row; try { row = tx.findRecordById("notification_deliveries", id) } catch { return }; if (row.getString("status") !== "LEASED" || row.getString("lease_id") !== leaseId) return; const attempts = row.getInt("attempt_count") + 1; row.set("attempt_count", attempts); row.set("lease_id", ""); row.set("lease_until", ""); if (outcome === "SENT") { row.set("status", "SENT"); row.set("sent_at", new Date().toISOString()); row.set("last_error", "") } else if (outcome === "PERMANENT") { row.set("status", "PERMANENTLY_FAILED"); row.set("last_error", String(error || "Permanent push failure").slice(0, 500)); try { const subscription = tx.findRecordById("push_subscriptions", row.getString("subscription_id")); subscription.set("revoked_at", new Date().toISOString()); tx.save(subscription); revoked = true } catch { /* already gone */ } } else { row.set("status", attempts >= 5 ? "PERMANENTLY_FAILED" : "RETRYABLE_FAILED"); row.set("scheduled_at", new Date(Date.now() + Math.min(3600, 30 * (2 ** attempts)) * 1000).toISOString()); row.set("last_error", String(error || "Push failed").slice(0, 500)) }; tx.save(row) }); return { revoked } }
module.exports = { claim, complete, generate, validate }
