routerAdd("POST", "/api/jornal/push/subscriptions", (event) => {
  if ($os.getenv("JORNAL_PUSH_ENABLED") !== "true") throw new ApiError(503, "Push notification sedang dinonaktifkan")
  const body = event.requestInfo().body || {}; const endpoint = String(body.endpoint || ""); const p256dh = String(body.keys && body.keys.p256dh || ""); const authKey = String(body.keys && body.keys.auth || ""); if (!endpoint.startsWith("https://") || !p256dh || !authKey) throw new ApiError(400, "Subscription push tidak valid")
  const companyIds = [...new Set((Array.isArray(body.companyIds) ? body.companyIds : []).map(String).filter(Boolean))]; for (const companyId of companyIds) require(`${__hooks}/company_access.js`).eventScope(event, companyId, {})
  const preferences = body.preferences && typeof body.preferences === "object" ? { invoice: body.preferences.invoice !== false, tax: body.preferences.tax !== false, documents: body.preferences.documents !== false, hideAmounts: body.preferences.hideAmounts !== false } : { invoice: true, tax: true, documents: true, hideAmounts: true }; const quietStart = Number(body.quietStartHour ?? 21); const quietEnd = Number(body.quietEndHour ?? 7); if (!Number.isInteger(quietStart) || quietStart < 0 || quietStart > 23 || !Number.isInteger(quietEnd) || quietEnd < 0 || quietEnd > 23) throw new ApiError(400, "Jam mode tenang tidak valid")
  const hash = $security.sha256(endpoint); let record; try { record = $app.findFirstRecordByFilter("push_subscriptions", "tenant_id = {:tenant} && endpoint_hash = {:hash}", { tenant: event.auth.id, hash }) } catch { record = new Record($app.findCollectionByNameOrId("push_subscriptions"), { tenant_id: event.auth.id, recipient_user_id: event.auth.id, endpoint_hash: hash }) }
  record.set("recipient_user_id", event.auth.id)
  record.set("endpoint", endpoint); record.set("p256dh", p256dh); record.set("auth_key", authKey); record.set("company_ids", companyIds); record.set("preferences", preferences); record.set("timezone", String(body.timezone || "Asia/Jakarta").slice(0, 60)); record.set("quiet_start_hour", quietStart); record.set("quiet_end_hour", quietEnd); record.set("revoked_at", ""); record.set("last_seen_at", new Date().toISOString()); $app.save(record)
  return event.json(201, { id: record.id, publicKey: $os.getenv("JORNAL_PUSH_VAPID_PUBLIC_KEY") || "" })
}, $apis.requireAuth())

routerAdd("DELETE", "/api/jornal/push/subscriptions", (event) => { const body = event.requestInfo().body || {}; const endpoint = String(body.endpoint || ""); if (!endpoint) throw new ApiError(400, "Endpoint wajib diisi"); let record; try { record = $app.findFirstRecordByFilter("push_subscriptions", "tenant_id = {:tenant} && endpoint_hash = {:hash}", { tenant: event.auth.id, hash: $security.sha256(endpoint) }) } catch { return event.json(200, { revoked: false }) }; record.set("revoked_at", new Date().toISOString()); $app.save(record); return event.json(200, { revoked: true }) }, $apis.requireAuth())

routerAdd("GET", "/api/jornal/push/config", (event) => event.json(200, { enabled: $os.getenv("JORNAL_PUSH_ENABLED") === "true" && Boolean($os.getenv("JORNAL_PUSH_VAPID_PUBLIC_KEY")), publicKey: $os.getenv("JORNAL_PUSH_VAPID_PUBLIC_KEY") || "" }), $apis.requireAuth())
