import { expect, test } from "@playwright/test"

const backend = "http://127.0.0.1:8090"
test("pays an invoice and offers a supplier money-out transfer", async ({ page, request }) => {
  await page.setViewportSize({ width: 360, height: 800 })
  const adminAuth = await request.post(`${backend}/api/collections/_superusers/auth-with-password`, { data: { identity: "e2e-admin@jornal.test", password: "StrongPass123!" } }); expect(adminAuth.ok()).toBeTruthy(); const admin = await adminAuth.json() as { token: string }
  const email = `invoice-e2e-${Date.now()}@example.com`; const createdUser = await request.post(`${backend}/api/collections/users/records`, { headers: { Authorization: admin.token }, data: { email, verified: true, password: "UserPass123!", passwordConfirm: "UserPass123!" } }); expect(createdUser.ok()).toBeTruthy(); const user = await createdUser.json() as { id: string; email: string; verified: boolean; collectionId: string; collectionName: string }; const impersonated = await request.post(`${backend}/api/collections/users/impersonate/${user.id}`, { headers: { Authorization: admin.token } }); const auth = await impersonated.json() as { token: string }
  const setup = await request.post(`${backend}/api/jornal/companies/setup`, { headers: { Authorization: auth.token }, data: { name: "Toko Invoice Browser", creationKey: "invoice-e2e-company", requestId: "invoice-e2e-company", initialSetup: true, profile: { businessName: "Toko Invoice Browser", businessType: "INDIVIDUAL", businessStartDate: "2026-01-01", fiscalYear: 2026, taxScheme: "UMKM_FINAL", pkpStatus: false, useAccountTracking: false, openingBalance: 0, taxReserveConfirmed: 0, lastBalanceCheckIn: null, lastCheckedBalance: null, lastCheckInDelta: null, onboardingCompletedAt: "2026-01-01T00:00:00.000Z", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" }, accounts: [
    { id: "browser-bca", name: "BCA Operasional", type: "BANK", bankName: "BCA", accountNumber: "1234567890", accountHolder: "Toko Invoice Browser", enabled: true, openingBalance: 0, includedInCash: true },
    { id: "browser-mandiri", name: "Mandiri Operasional", type: "BANK", bankName: "Mandiri", accountNumber: "9876543210", accountHolder: "Toko Invoice Browser", enabled: true, openingBalance: 0, includedInCash: true },
  ] } }); expect(setup.ok()).toBeTruthy(); const company = await setup.json() as { id: string }
  await page.addInitScript(({ token, record }) => localStorage.setItem("pocketbase_auth", JSON.stringify({ token, record })), { token: auth.token, record: user })
  await page.goto(`/invoices?company=${company.id}`)
  const unpaidCard = page.getByText("Belum bayar", { exact: true }).locator("..")
  const overdueCard = page.getByText("Terlambat", { exact: true }).locator("..")
  const unpaidAmountBox = await unpaidCard.getByText("Rp0", { exact: true }).boundingBox()
  const overdueAmountBox = await overdueCard.getByText("Rp0", { exact: true }).boundingBox()
  expect(unpaidAmountBox).toBeTruthy(); expect(overdueAmountBox).toBeTruthy()
  expect(Math.abs(unpaidAmountBox!.y - overdueAmountBox!.y)).toBeLessThanOrEqual(1)
  await expect(page.getByLabel("Cari invoice")).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole("button", { name: "Cari" }).click()
  await expect(page).toHaveURL(/\/search/)
  await expect(page.getByLabel("Cari minimal 2 karakter")).toBeFocused()
  await page.goto(`/settings?company=${company.id}`)
  await page.getByRole("button", { name: "Reset data company ini" }).click()
  const resetDialog = page.getByRole("dialog", { name: "Reset data Toko Invoice Browser?" })
  await expect(resetDialog).toBeVisible()
  await expect(resetDialog.getByText("Company lain tidak akan terpengaruh.")).toBeVisible()
  await resetDialog.getByRole("button", { name: "Batal" }).click()
  await expect(resetDialog).toBeHidden()
  await page.goto(`/settings/invoice?company=${company.id}`)
  await page.getByRole("combobox", { name: "Satuan default" }).click()
  await page.getByRole("option", { name: "Lusin" }).click()
  await page.getByLabel(/BCA.*1234567890/).check()
  await page.getByLabel(/Mandiri.*9876543210/).check()
  await page.getByRole("button", { name: "Simpan Pengaturan" }).click()
  await expect(page.getByRole("button", { name: "Tersimpan" })).toBeVisible()
  await page.goto(`/customers/new?company=${company.id}`); await page.getByLabel("Nama").fill("Pelanggan Browser"); await page.getByLabel("Kode pos").fill("00123"); await page.getByRole("button", { name: "Simpan pelanggan" }).click(); await expect(page.getByRole("heading", { name: "Pelanggan Browser" })).toBeVisible(); await page.getByRole("link", { name: "Buat Invoice" }).click()
  await page.getByRole("combobox", { name: "Pelanggan" }).click()
  const customerSearch = page.getByRole("searchbox", { name: "Cari pelanggan…" })
  await expect(customerSearch).toBeFocused()
  await customerSearch.fill("browser")
  await expect(page.getByRole("option", { name: "Pelanggan Browser" })).toBeVisible()
  await customerSearch.fill("tidak ditemukan")
  await expect(page.getByText("Tidak ada hasil untuk “tidak ditemukan”")).toBeVisible()
  await customerSearch.fill("pelanggan")
  await page.getByRole("option", { name: "Pelanggan Browser" }).click()
  const today = new Date()
  const officialInvoiceNumber = `${today.getFullYear()}/${String(today.getMonth() + 1).padStart(2, "0")}/INV/001`
  const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1)
  const shortMonths = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"]
  await expect(page.getByLabel("Jatuh tempo")).toContainText(`${tomorrow.getDate()} ${shortMonths[tomorrow.getMonth()]} ${tomorrow.getFullYear()}`)
  const quantityBox = await page.getByLabel("Jumlah").locator("xpath=..").boundingBox()
  const unitBox = await page.getByLabel("Satuan").locator("xpath=..").boundingBox()
  const priceBox = await page.getByLabel("Harga/unit").locator("xpath=..").boundingBox()
  expect(quantityBox).toBeTruthy(); expect(unitBox).toBeTruthy(); expect(priceBox).toBeTruthy()
  expect(Math.abs(quantityBox!.y - unitBox!.y)).toBeLessThanOrEqual(1)
  expect(Math.abs(quantityBox!.height - unitBox!.height)).toBeLessThanOrEqual(1)
  expect(priceBox!.y).toBeGreaterThan(quantityBox!.y + quantityBox!.height)
  expect(priceBox!.width).toBeGreaterThan(quantityBox!.width * 1.8)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole("button", { name: "Tambah item" }).click()
  const secondItem = page.getByRole("button", { name: "Duplikat item 2" }).locator('xpath=ancestor::div[@data-slot="card"]')
  await expect(secondItem.getByRole("combobox", { name: "Satuan" })).toContainText("Lusin")
  await page.getByRole("button", { name: "Hapus item 2" }).click()
  await page.getByRole("combobox", { name: "Ketik nama produk" }).fill("Jasa browser")
  await page.getByLabel("Jumlah").fill("2")
  await page.getByLabel("Harga/unit").fill("100000")
  await page.getByLabel("Pajak (%)").fill("")
  await page.getByLabel("Pajak (%)").pressSequentially("0,5")
  await expect(page.getByLabel("Pajak (%)")).toHaveValue("0,5")
  await expect(page.getByText("Rp201.000")).toBeVisible()
  await page.getByLabel("Pajak (%)").fill("invalid")
  await expect(page.getByRole("button", { name: "Terbitkan" })).toBeDisabled()
  await page.getByLabel("Pajak (%)").fill("0")
  await page.getByLabel("Jumlah").fill("")
  await page.getByLabel("Jumlah").pressSequentially("2,5")
  await expect(page.getByLabel("Jumlah")).toHaveValue("2,5")
  await expect(page.getByText("Rp250.000")).toBeVisible()
  await page.getByLabel("Jumlah").fill("2,5001")
  await expect(page.getByLabel("Jumlah")).toHaveAttribute("aria-invalid", "true")
  await expect(page.getByRole("button", { name: "Terbitkan" })).toBeDisabled()
  await page.getByLabel("Jumlah").fill("2")
  await page.getByLabel("Harga/unit").fill("9007199254740993")
  await expect(page.getByLabel("Harga/unit")).toHaveValue("9.007.199.254.740.993")
  await expect(page.getByRole("button", { name: "Terbitkan" })).toBeDisabled()
  await page.getByLabel("Harga/unit").fill("100000")
  await page.getByRole("button", { name: "Duplikat item 1" }).click()
  const duplicate = page.getByRole("button", { name: "Duplikat item 2" }).locator('xpath=ancestor::div[@data-slot="card"]')
  await expect(duplicate.getByRole("combobox", { name: "Ketik nama produk" })).toHaveValue("Jasa browser")
  await expect(duplicate.getByLabel("Jumlah")).toHaveValue("2")
  await expect(duplicate.getByRole("combobox", { name: "Satuan" })).toContainText("Lusin")
  await expect(duplicate.getByLabel("Harga/unit")).toHaveValue("100.000")
  await expect(page.getByText("Rp400.000")).toBeVisible()
  await page.getByRole("button", { name: "Hapus item 2" }).click()
  await expect(page.getByText("Rp200.000")).toBeVisible()
  await page.getByRole("button", { name: "Terbitkan" }).click(); await expect(page.getByRole("heading", { name: officialInvoiceNumber })).toBeVisible(); await expect(page.getByText("Belum bayar · revisi", { exact: false })).toBeVisible()
  await expect(page.getByText("1234567890", { exact: false })).toBeVisible()
  await expect(page.getByText("9876543210", { exact: false })).toBeVisible()
  await page.goto(`/invoices?company=${company.id}`)
  const invoiceCard = page.getByText(officialInvoiceNumber, { exact: false }).locator("xpath=ancestor::a[1]")
  await expect(invoiceCard.getByText(/· Pelanggan/)).toBeVisible()
  await expect(invoiceCard.getByTitle("Jatuh tempo")).toBeVisible()
  await invoiceCard.click()
  await page.getByRole("link", { name: "Revisi" }).click()
  await page.getByLabel("Pengiriman").fill("Kurir revisi")
  await page.getByRole("button", { name: "Simpan Revisi" }).click()
  await expect(page.getByRole("heading", { name: officialInvoiceNumber })).toBeVisible()
  await expect(page.getByText("Kurir revisi", { exact: false })).toBeVisible()
  await page.getByRole("combobox", { name: "Rekening" }).click()
  await page.getByRole("option", { name: /BCA Operasional/ }).click()
  await page.getByRole("button", { name: "Catat pembayaran" }).click()
  await expect(page.getByRole("heading", { name: "Invoice lunas" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Ubah status pembayaran" })).toHaveCount(0)
  await expect(page.getByLabel("Alasan koreksi pembayaran")).toHaveCount(0)
  await page.getByRole("button", { name: "Batalkan pembayaran" }).click()
  const correctionDialog = page.getByRole("dialog", { name: "Batalkan catatan pembayaran?" })
  await expect(correctionDialog.getByRole("button", { name: "Batalkan pembayaran" })).toBeDisabled()
  await correctionDialog.getByRole("button", { name: "Batal", exact: true }).click()
  await page.getByRole("link", { name: "Koreksi total terbayar" }).click()
  await expect(page.getByRole("heading", { name: "Koreksi total terbayar" })).toBeVisible()
  await page.getByLabel("Total sudah dibayar setelah koreksi").fill("210000")
  await page.getByLabel("Alasan perubahan pembayaran").fill("Transfer ternyata lebih besar")
  await expect(page.getByText("Lebih bayar Rp10.000. Total invoice tetap Rp200.000.")).toBeVisible()
  await page.getByRole("button", { name: "Simpan koreksi pembayaran" }).click()
  await expect(page).toHaveURL(/\/invoices\/[^/]+$/)
  await expect(page.getByRole("status").filter({ hasText: "Koreksi pembayaran berhasil disimpan." })).toBeVisible()
  await expect(page.getByText("Terbayar Rp210.000 dari total Rp200.000 · Lebih bayar Rp10.000")).toBeVisible()
  await page.goto(`/invoices?company=${company.id}`)
  const overpaidCard = page.getByText(officialInvoiceNumber, { exact: false }).locator("xpath=ancestor::a[1]")
  await expect(overpaidCard.getByText("Lebih bayar", { exact: true })).toBeVisible()
  await expect(overpaidCard.getByText("Terbayar Rp210.000 · Lebih bayar Rp10.000")).toBeVisible()
  await overpaidCard.click()
  await page.getByRole("link", { name: "Koreksi total terbayar" }).click()
  await page.getByLabel("Total sudah dibayar setelah koreksi").fill("100000")
  await page.getByLabel("Alasan perubahan pembayaran").fill("Koreksi nominal transfer")
  await page.getByRole("button", { name: "Simpan koreksi pembayaran" }).click()
  await expect(page).toHaveURL(/\/invoices\/[^/]+$/)
  await expect(page.getByRole("status").filter({ hasText: "Koreksi pembayaran berhasil disimpan." })).toBeVisible()
  await expect(page.getByText("Dibayar sebagian · revisi", { exact: false })).toBeVisible()
  await page.goto(`/invoices?company=${company.id}`)
  const partialCard = page.getByText(officialInvoiceNumber, { exact: false }).locator("xpath=ancestor::a[1]")
  await expect(partialCard.getByText("Dibayar sebagian")).toBeVisible()
  await expect(partialCard.getByText("Terbayar Rp100.000")).toBeVisible()
  await expect(partialCard.getByText("Sisa tagihan")).toBeVisible()
  await expect(partialCard.locator("strong").filter({ hasText: "Rp100.000" })).toBeVisible()
  await partialCard.click()
  await expect(page.getByText("Dibayar sebagian · revisi", { exact: false })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Ubah status pembayaran" })).toHaveCount(0)
  await page.getByRole("combobox", { name: "Rekening" }).click()
  await page.getByRole("option", { name: /BCA Operasional/ }).click()
  await page.getByRole("button", { name: "Catat pembayaran" }).click()
  await expect(page.getByRole("heading", { name: "Invoice lunas" })).toBeVisible()
  await page.getByRole("link", { name: "Catat transfer ke supplier" }).click()
  await expect(page).toHaveURL(/\/add/)
  await expect(page.getByLabel("Keterangan")).toHaveValue(`Bayar supplier untuk invoice ${officialInvoiceNumber}`)
  await expect(page.getByText(`Invoice terkait: ${officialInvoiceNumber} · Total invoice Rp200.000`)).toBeVisible()
  await expect(page.getByLabel("Cari invoice terkait")).toHaveCount(0)
  await expect(page.getByRole("combobox", { name: "Kaitkan ke invoice" })).toHaveCount(0)
  await expect(page.getByRole("combobox", { name: "Rekening asal" })).toContainText("BCA")
  await page.getByRole("button", { name: "Simpan" }).click()
  await expect(page.getByText("Jumlah harus berupa rupiah utuh yang valid dan lebih dari nol.")).toBeVisible()
  await page.getByLabel("Jumlah").fill("50000")
  await expect(page.getByLabel("Nama supplier (opsional)")).toHaveValue("")
  await page.getByRole("button", { name: "Simpan" }).click()
  await expect(page).toHaveURL(/\/transactions/)
  await expect(page.getByText(`Bayar supplier untuk invoice ${officialInvoiceNumber}`, { exact: true })).toBeVisible()
  await page.getByText(`Bayar supplier untuk invoice ${officialInvoiceNumber}`, { exact: true }).click()
  await expect(page.getByText("Invoice terkait", { exact: true })).toBeVisible()
  await expect(page.getByRole("link", { name: officialInvoiceNumber })).toBeVisible()
  await expect(page.getByRole("button", { name: "Pakai perangkat" })).toHaveCount(0)
})
