import { useEffect, useState } from "react"
import { useNavigate } from "@tanstack/react-router"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { TextField } from "@/components/ui/text-field"
import { createCustomer, getCustomer, updateCustomer } from "@/lib/invoice-client"

const empty = { name: "", email: "", phone: "", addressLine1: "", addressLine2: "", district: "", city: "", province: "", postalCode: "" }
export function CustomerFormPage({ customerId, returnTo }: { customerId?: string; returnTo?: string }) {
  const navigate = useNavigate(); const [form, setForm] = useState(empty); const [revision, setRevision] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("")
  useEffect(() => { if (customerId) void getCustomer(customerId).then(({ customer }) => { setForm({ name: customer.name, email: customer.email || "", phone: customer.phone || "", addressLine1: customer.addressLine1 || "", addressLine2: customer.addressLine2 || "", district: customer.district || "", city: customer.city || "", province: customer.province || "", postalCode: customer.postalCode || "" }); setRevision(customer.revision) }).catch((cause) => setError(String(cause))) }, [customerId])
  const field = (key: keyof typeof form, label: string, required = false) => <TextField label={label} value={form[key]} onChange={(value) => setForm((current) => ({ ...current, [key]: value }))} required={required} />
  const save = async () => { setBusy(true); setError(""); try { const result = customerId ? await updateCustomer(customerId, { ...form, expectedRevision: revision }) : await createCustomer(form); if (returnTo === "/invoices/new") await navigate({ to: "/invoices/new", search: { customer: result.customer.id } }); else await navigate({ to: "/customers/$customerId", params: { customerId: result.customer.id } }) } catch (cause) { setError(cause instanceof Error ? cause.message : "Pelanggan gagal disimpan") } finally { setBusy(false) } }
  return <div className="space-y-4 pb-8"><div><h1 className="text-2xl">{customerId ? "Edit pelanggan" : "Tambah pelanggan"}</h1><p className="text-sm text-muted-foreground">Informasi kontak dan alamat.</p></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Card><CardContent className="grid gap-4 p-4"><h2 className="font-semibold">Informasi Kontak</h2>{field("name", "Nama", true)}{field("email", "Email")}{field("phone", "Telepon / WhatsApp")}<h2 className="mt-2 font-semibold">Alamat</h2>{field("addressLine1", "Alamat baris 1")}{field("addressLine2", "Alamat baris 2")}<div className="grid gap-4 sm:grid-cols-2">{field("district", "Kecamatan")}{field("city", "Kota / Kabupaten")}{field("province", "Provinsi")}{field("postalCode", "Kode pos")}</div></CardContent></Card><Button className="w-full" disabled={busy || !form.name.trim()} onClick={() => void save()}>{busy ? "Menyimpan…" : "Simpan pelanggan"}</Button></div>
}
