import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { Link } from "@tanstack/react-router"
import { CalendarClock, ChevronRight, FileText, ListFilter, Plus, Search, Settings2, TriangleAlert, Users } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { SelectField } from "@/components/ui/select-field"
import { TextField } from "@/components/ui/text-field"
import { formatRupiah } from "@/lib/format"
import { getInvoiceSummary, listInvoices } from "@/lib/invoice-client"

export function InvoicesPage() {
  const [status, setStatus] = useState(""); const [search, setSearch] = useState("")
  const summary = useQuery({ queryKey: ["invoice", "summary"], queryFn: getInvoiceSummary }); const invoices = useQuery({ queryKey: ["invoice", "list", status, search], queryFn: () => listInvoices({ status, search }) })
  return <div className="space-y-4 pb-8"><header className="flex items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl"><FileText className="size-5 text-primary" aria-hidden="true" />Invoice</h1><p className="text-sm text-muted-foreground">Tagihan pelanggan dan penerimaan kas.</p></div><Link to="/invoices/new" search={{}} className="inline-flex h-10 items-center gap-2 rounded-full bg-[var(--main-dark)] px-4 text-sm font-semibold text-white"><Plus className="size-4" />Buat</Link></header>
    <div className="grid grid-cols-2 gap-3"><Card><CardContent className="p-4"><p className="flex items-center gap-1.5 text-xs text-muted-foreground"><CalendarClock className="size-3.5 text-amber-600" aria-hidden="true" />Belum Dibayar</p><p className="mt-1 font-semibold tabular-nums">{formatRupiah(summary.data?.unpaidTotal || 0)}</p><p className="text-xs">{summary.data?.unpaidCount || 0} invoice</p></CardContent></Card><Card><CardContent className="p-4"><p className="flex items-center gap-1.5 text-xs text-muted-foreground"><TriangleAlert className="size-3.5 text-red-600" aria-hidden="true" />Lewat Jatuh Tempo</p><p className="mt-1 font-semibold text-red-700 tabular-nums">{formatRupiah(summary.data?.overdueTotal || 0)}</p><p className="text-xs">{summary.data?.overdueCount || 0} invoice</p></CardContent></Card></div>
    <div className="grid grid-cols-[1fr_minmax(9rem,auto)] gap-2"><TextField label="Cari nomor atau pelanggan" icon={Search} value={search} onChange={setSearch} /><SelectField label="Status" icon={ListFilter} value={status} onChange={setStatus} options={[{ value: "", label: "Semua" }, { value: "DRAFT", label: "Draft" }, { value: "UNPAID", label: "Belum dibayar" }, { value: "PAID", label: "Lunas" }, { value: "VOID", label: "Dibatalkan" }]} /></div>
    <div className="space-y-3">{invoices.data?.items.map((invoice) => <Link key={invoice.id} to="/invoices/$invoiceId" params={{ invoiceId: invoice.id }} className="flex items-center gap-3 rounded-xl border bg-white p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#f1f5fd] text-[#16579d]"><FileText className="size-4" aria-hidden="true" /></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{invoice.invoiceNumber || "Draft invoice"}</p><p className="text-xs text-muted-foreground">{invoice.issueDate} · jatuh tempo {invoice.dueDate} · {invoice.status}</p></div><strong className="shrink-0 tabular-nums">{formatRupiah(invoice.grandTotal)}</strong><ChevronRight className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" /></Link>)}</div>{!invoices.isLoading && !invoices.data?.items.length && <Card><CardContent className="p-8 text-center"><FileText className="mx-auto mb-2 size-7 text-muted-foreground" />Belum ada invoice.</CardContent></Card>}
    <div className="flex gap-4 text-sm"><Link to="/customers" className="inline-flex items-center gap-1.5 font-semibold text-[var(--link)]"><Users className="size-4" aria-hidden="true" />Kelola Pelanggan</Link><Link to="/settings/invoice" className="inline-flex items-center gap-1.5 font-semibold text-[var(--link)]"><Settings2 className="size-4" aria-hidden="true" />Pengaturan Invoice</Link></div>
  </div>
}
