import { useMemo, useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { Link } from "@tanstack/react-router"
import { TextField } from "@/components/ui/text-field"
import { listCustomers, listInvoices } from "@/lib/invoice-client"
import { useTransactions } from "@/lib/queries"
import { formatRupiah } from "@/lib/format"
import { searchDocuments } from "@/lib/document-client"

export function SearchPage() { const [search, setSearch] = useState(""); const customers = useQuery({ queryKey: ["search", "customers", search], queryFn: () => listCustomers({ search, perPage: 10 }), enabled: search.length >= 2 }); const invoices = useQuery({ queryKey: ["search", "invoices", search], queryFn: () => listInvoices({ search, perPage: 10 }), enabled: search.length >= 2 }); const documents = useQuery({ queryKey: ["search", "documents", search], queryFn: () => searchDocuments(search), enabled: search.length >= 2 }); const { data: transactions = [] } = useTransactions(); const local = useMemo(() => search.length < 2 ? [] : transactions.filter((item) => [item.description, item.supplierCustomer, item.notes].some((value) => value?.toLowerCase().includes(search.toLowerCase()))).slice(0, 10), [transactions, search]); return <div className="space-y-4 pb-8"><header><h1 className="text-2xl">Pencarian</h1><p className="text-sm text-muted-foreground">Transaksi, pelanggan, invoice, dan dokumen dalam company aktif.</p></header><TextField label="Cari minimal 2 karakter" value={search} onChange={setSearch} autoFocus />{local.map((item) => <Link key={item.id} to="/transactions/$transactionId" params={{ transactionId: item.id }} className="flex justify-between rounded-xl border bg-white p-3"><span>Transaksi · {item.description}</span><strong>{formatRupiah(item.amount)}</strong></Link>)}{customers.data?.items.map((item) => <Link key={item.id} to="/customers/$customerId" params={{ customerId: item.id }} className="block rounded-xl border bg-white p-3">Pelanggan · {item.name}</Link>)}{invoices.data?.items.map((item) => <Link key={item.id} to="/invoices/$invoiceId" params={{ invoiceId: item.id }} className="flex justify-between rounded-xl border bg-white p-3"><span>Invoice · {item.invoiceNumber || "Draft"}</span><strong>{formatRupiah(item.grandTotal)}</strong></Link>)}{documents.data?.items.map((item) => <Link key={item.document.id} to="/inbox/$documentId" params={{ documentId: item.document.id }} className="block rounded-xl border bg-white p-3">Dokumen · {item.summary.merchantName || item.summary.description || item.document.filename}</Link>)}</div> }
