import { useEffect, useState } from "react"
import { activeCompany } from "@/lib/companies"
import { mirrorState, restoreState } from "@/lib/local-db"
import { Button } from "@/components/ui/button"
import { TextField } from "@/components/ui/text-field"
import { parseAmountInput } from "@/lib/format"

interface Template { id: string; name: string; description: string; direction: "MONEY_IN" | "MONEY_OUT"; amount: number | null }
function key() { const company = activeCompany(); return `jornal.transaction-templates.${company?.tenantId}.${company?.id}.v1` }
export function TransactionTemplatesPage() { const [items, setItems] = useState<Template[]>([]); const [form, setForm] = useState<{ name: string; description: string; direction: "MONEY_IN" | "MONEY_OUT"; amount: string }>({ name: "", description: "", direction: "MONEY_OUT", amount: "" }); useEffect(() => { void restoreState(key()).then((value) => setItems(Array.isArray(value) ? value as Template[] : [])) }, []); const save = (next: Template[]) => { setItems(next); void mirrorState(key(), next) }; return <div className="space-y-4 pb-8"><header><h1 className="text-2xl">Template Transaksi</h1><p className="text-sm text-muted-foreground">Template hanya mengisi form; tidak pernah mencatat uang otomatis.</p></header><div className="grid gap-3 rounded-xl border bg-white p-4"><TextField label="Nama template" value={form.name} onChange={(name) => setForm({ ...form, name })} /><TextField label="Deskripsi" value={form.description} onChange={(description) => setForm({ ...form, description })} /><TextField label="Nominal opsional" type="amount" value={form.amount} onChange={(amount) => setForm({ ...form, amount })} /><select className="h-12 rounded-xl border px-3" value={form.direction} onChange={(event) => setForm({ ...form, direction: event.target.value as "MONEY_IN" | "MONEY_OUT" })}><option value="MONEY_OUT">Uang keluar</option><option value="MONEY_IN">Uang masuk</option></select><Button disabled={!form.name.trim() || !form.description.trim()} onClick={() => { save([...items, { id: crypto.randomUUID(), name: form.name.trim(), description: form.description.trim(), direction: form.direction, amount: form.amount ? parseAmountInput(form.amount) : null }]); setForm({ name: "", description: "", direction: "MONEY_OUT", amount: "" }) }}>Simpan template</Button></div>{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border bg-white p-3"><a href={`/add?direction=${item.direction}&amount=${item.amount || ""}&description=${encodeURIComponent(item.description)}`}><strong>{item.name}</strong><p className="text-xs text-muted-foreground">{item.description}</p></a><button className="text-xs text-red-700" onClick={() => save(items.filter((candidate) => candidate.id !== item.id))}>Hapus</button></div>)}</div> }
