import { useRef, useState } from "react"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { Button } from "@/components/ui/button"
import { useAppDialog } from "@/components/ui/app-dialog-context"
import { loadCompanyLogo, removeCompanyLogo, uploadCompanyLogo } from "@/lib/companies"
import type { Company } from "@/lib/types"

export function CompanyLogo({ company, className = "size-10" }: { company: Company; className?: string }) {
  const logo = useQuery({ queryKey: ["company-logo", company.id, company.logoAssetId], queryFn: () => loadCompanyLogo(company), enabled: Boolean(company.logoAssetId), staleTime: Infinity })
  return logo.data?.dataUrl ? <img src={logo.data.dataUrl} alt={`Logo ${company.name}`} className={`${className} rounded-lg object-contain`} /> : <span className={`${className} grid place-items-center rounded-lg bg-secondary font-semibold`}>{company.name.slice(0, 2).toUpperCase()}</span>
}
export function CompanyLogoEditor({ company }: { company: Company }) {
  const dialog = useAppDialog()
  const input = useRef<HTMLInputElement>(null); const client = useQueryClient(); const [preview, setPreview] = useState<{ file: File; url: string } | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false)
  const choose = (file?: File) => { if (!file) return; if (![/^image\/png$/, /^image\/jpeg$/, /^image\/webp$/].some((pattern) => pattern.test(file.type)) || file.size > 2 * 1024 * 1024) { setMessage("Pilih PNG, JPEG, atau WebP sampai 2 MB."); return }; if (preview) URL.revokeObjectURL(preview.url); setPreview({ file, url: URL.createObjectURL(file) }); setMessage("") }
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["jornal", "companies"] }); await client.invalidateQueries({ queryKey: ["company-logo", company.id] }) }
  return <div className="rounded-xl border bg-white p-4"><div className="flex items-center gap-4">{preview ? <img src={preview.url} alt="Preview logo baru" className="h-20 w-32 object-contain" /> : <CompanyLogo company={company} className="h-20 w-32" />}<div><p className="font-semibold">Logo Company</p><p className="text-xs text-muted-foreground">PNG/JPEG/WebP, maksimal 2 MB. Logo horizontal dipertahankan utuh.</p></div></div>{message && <p className="mt-2 text-xs text-red-700">{message}</p>}<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy || company.status !== "ACTIVE"} onClick={() => input.current?.click()}>{company.logoAssetId ? "Ganti Logo" : "Unggah Logo"}</Button>{preview && <Button size="sm" disabled={busy} onClick={() => { setBusy(true); void uploadCompanyLogo(company, preview.file).then(refresh).then(() => { URL.revokeObjectURL(preview.url); setPreview(null); setMessage("Logo tersimpan.") }).catch((error) => setMessage(String(error))).finally(() => setBusy(false)) }}>Simpan Logo</Button>}{preview && <Button size="sm" variant="ghost" onClick={() => { URL.revokeObjectURL(preview.url); setPreview(null) }}>Batal</Button>}{company.logoAssetId && !preview && <Button size="sm" variant="ghost" disabled={busy || company.status !== "ACTIVE"} onClick={() => void dialog.confirm({ title: "Hapus logo company?", description: "Logo akan dihapus dari profil dan invoice berikutnya. Invoice yang sudah terbit tetap memakai snapshot logo lama.", confirmLabel: "Hapus logo", tone: "destructive" }).then((confirmed) => { if (!confirmed) return; setBusy(true); return removeCompanyLogo(company).then(refresh).catch((error) => setMessage(String(error))).finally(() => setBusy(false)) })}>Hapus Logo</Button>}<input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => choose(event.target.files?.[0])} /></div></div>
}
